# Generated by Django 5.2.7 on 2025-10-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
